"""comment migration

Revision ID: 409d459d689a
Revises: 8d64910296ce
Create Date: 2022-05-15 10:57:34.657909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409d459d689a'
down_revision = '8d64910296ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
